version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "aacecandev"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
      separator: ":"
      suffix: "Update GitHub Actions"
    assignees:
      - "aacecandev"
    ignore:
      - dependency-name: "aacecandev/action-secrets"
        versions:
          - ">=0.0.0"
    versioning-strategy: "auto"
    target-branch: "main"
