name: "Build and Push Docker Image"

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker image metadata
        id: docker_image_metadata
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}"
          flavor: latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.docker_image_metadata.outputs.tags }}
          labels: ${{ steps.docker_image_metadata.outputs.labels }}
          push: true
